import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

// const geistSans = Geist({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-geist-sans',
// });

// const geistMono = Geist_Mono({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-geist-mono',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Toaster position='top-right' reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
